server:
  port: 8083
spring:
  activemq:
    broker-url: tcp://localhost:61616
    password: Expect-Eggs-Why_Goat!
    packages:
      trust-all: true
    user: myuser
    queues:
      playlist:
        produce:  com.jamify.ai.playlist-gen
        consume: com.jamify.orchestrator.playlist-done
  application:
    name: orchestration

config:
  engine:
    url:
      base: http://localhost:8082
    jamify-engine-api-key: super-secret-dev-key