server:
    port: 8083
spring:
    activemq:
        broker-url: tcp://activemq:61616
        password: admin
        packages:
            trust-all: true
        queues:
            playlist:
                produce:  jamify.ai.playlist-gen
                consume: jamify.orchestrator.playlist-done
            notification:
                produce:  jamify.notify.notification

    application:
        name: orchestration

config:
    engine:
        url:
            base: ${JAMIFY_ENGINE_BASE_URL}
        jamify-engine-api-key: ${JAMIFY_ENGINE_API_KEY}
