
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: myusr
    password: mypwd
config:
  engine:
    url:
      base: http://localhost:8082
    jamify-engine-api-key: super-secret-dev-key