server:
    port: 8083
spring:
    activemq:
        broker-url: tcp://localhost:61616
        password: Expect-Eggs-Why_Goat!
        packages:
            trust-all: true
        user: myuser
        queues:
            playlist:
                produce:  jamify.ai.playlist-gen
                consume: jamify.orchestrator.playlist-done
    application:
        name: orchestration
