server:
    port: 8083
spring:
    activemq:
        broker-url: tcp://localhost:61616
        password: Expect-Eggs-Why_Goat!
        packages:
            trust-all: true
        user: myuser
        queues:
            playlist:
                produce:  playlistDemandQueue
                consume: playlistResultQueue
    application:
        name: orchestration
