name: Jamify orchestration microservice CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./orchestration

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        env:
          SPRING_PROFILES_ACTIVE: test
        run: mvn -B package --file pom.xml -Dspring.profiles.active=test

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifact
          path: target/*.jar

  docker:
    name: "Docker Build and Push"
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-artifact

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/jamify-orchestrator
          tags: |
            type=ref,event=branch
            type=sha,format=short
            type=raw,value=latest

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/jamify-orchestrator:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/jamify-orchestrator:buildcache,mode=max
